apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: polarpoint
  description: polarpoint.io

  links:
    - url: http://polarpoint.io/
      title: Website
    - url: https://polarpoint.atlassian.com
      title: Wiki
spec:
  type: organization
  profile:
    displayName: Polarpoint.io
    email: backstage@polarpoint.io
    picture: https://github.com/polarpoint-io/images-icons-avatars/blob/master/assets/img/polarpoint.png
  children: [group:engineering]

